[ 2025-04-08 13:11:07,430 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\main.py on line number 24 error messgae cannot do slice indexing on DatetimeIndex with these indexers [2025-04-0823:00:00] of type str
[ 2025-04-08 13:12:43,179 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\main.py on line number 24 error messgae cannot unpack non-iterable NoneType object
[ 2025-04-08 13:13:57,479 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\main.py on line number 24 error messgae cannot unpack non-iterable NoneType object
[ 2025-04-08 13:14:57,105 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\main.py on line number 24 error messgae cannot unpack non-iterable NoneType object
[ 2025-04-08 13:16:50,700 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\main.py on line number 24 error messgae cannot unpack non-iterable NoneType object
[ 2025-04-08 13:19:19,156 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\main.py on line number 24 error messgae cannot unpack non-iterable NoneType object
[ 2025-04-08 13:20:28,575 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\main.py on line number 26 error messgae BuildModel.predict_next_day() missing 1 required positional argument: 'min_max_scale'
[ 2025-04-08 14:11:21,433 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 30 error messgae [Errno 22] Invalid argument: 'src/data_set/Thanjavur_2024-04-01 00:00:00_1_year_weather.csv'
[ 2025-04-08 14:11:21,434 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 115 error messgae No columns to parse from file
[ 2025-04-08 14:11:52,676 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 30 error messgae [Errno 22] Invalid argument: 'src/data_set/Thanjavur_2024-04-01 00:00:00_1_year_weather.csv'
[ 2025-04-08 14:11:52,677 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 115 error messgae No columns to parse from file
[ 2025-04-08 15:32:13,911 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 30 error messgae [Errno 22] Invalid argument: 'src/data_set/Thanjavur_2024-04-01 00:00:00_1_year_weather.csv'
[ 2025-04-08 15:32:13,912 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 112 error messgae No columns to parse from file
[ 2025-04-08 15:32:35,698 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 30 error messgae [Errno 22] Invalid argument: 'src/data_set/Thanjavur_2024-04-01 00:00:00_1_year_weather.csv'
[ 2025-04-08 15:32:35,701 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 112 error messgae No columns to parse from file
[ 2025-04-08 15:32:46,614 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 30 error messgae [Errno 22] Invalid argument: 'src/data_set/Thanjavur_2024-04-01 00:00:00_1_year_weather.csv'
[ 2025-04-08 15:35:28,369 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 30 error messgae [Errno 22] Invalid argument: 'src/data_set/Thanjavur_2024-04-01 00:00:00_1_year_weather.csv'
[ 2025-04-08 15:35:49,204 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 30 error messgae [Errno 22] Invalid argument: 'src/data_set/Thanjavur_2024-04-01 00:00:00_1_year_weather.csv'
[ 2025-04-08 15:36:20,981 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 30 error messgae [Errno 2] No such file or directory: 'src/data_set/Thanjavur_2024-00-04/01/24_1_year_weather.csv'
[ 2025-04-08 15:37:32,283 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 30 error messgae [Errno 2] No such file or directory: 'src/data_set/Thanjavur_2025-37-04/08/25_1_year_weather.csv'
[ 2025-04-08 15:37:57,068 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 43 error messgae 'forecast'
[ 2025-04-08 15:38:36,783 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 43 error messgae 'forecast'
[ 2025-04-08 15:39:13,557 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 43 error messgae 'forecast'
[ 2025-04-08 15:40:17,150 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 46 error messgae string indices must be integers, not 'str'
[ 2025-04-08 15:40:50,724 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 47 error messgae string indices must be integers, not 'str'
[ 2025-04-08 15:42:27,750 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 47 error messgae 'current'
[ 2025-04-08 15:43:24,597 ] 14 root - INFO - Error occured in python script name at G:\RealtimeProjects\LiveWeatherPrediction\src\components\data_integstion.py on line number 47 error messgae 'time'
